import Head from "next/head";

type LayoutProps = {
  children: React.ReactNode;
};

const siteTitle = "Tolistore";

export const LayoutComponent: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>{siteTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
    </>
  );
};

LayoutComponent.displayName = "Layout";
